FROM elixir:alpine

RUN apk add bash 

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force 

ENV APP_HOME /app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

EXPOSE 4000
